{{- if .Values.ui.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "counter-application.fullname" . }}-postgres-config
  labels:
    {{- include "counter-application.labels" . | nindent 4 }}
data:
  POSTGRES_HOST: {{ include "counter-application.fullname" . }}-postgres
  POSTGRES_DB: {{ .Values.postgresql.dbName | quote }}
  POSTGRES_USER: {{ .Values.postgresql.dbUser | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.dbPassword | quote }}
{{- end }}