{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "counter-application.fullname" . }}-postgres
  labels:
    {{- include "counter-application.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "counter-application.selectorLabels" . | nindent 4 }}
  ports:
    - port: 5432
      targetPort: 5432
{{- end }}
